//@version=4
// © barrett38
study(title="Stochastic Extremes", shorttitle="Stcohastic Extremes", overlay=true, resolution="")

// STOCHASTIC
stochLevel = input(16, title="Stoch Level, Default at 16", minval=1, step=1)
stoch_low = 35 - stochLevel
stoch_high = 65 + stochLevel

k = (sma(stoch(close, high, low, (input(17, title="K", minval=1))), (3)))
d = (sma(k, (input(3, title="D", minval=1))))

extreme_low = (k[1]<d[1] and (k>d)) and 
   (( k<stoch_low ) or ( d<stoch_low ))
plotshape(extreme_low,
      style=shape.xcross,
      color=#26A69A,
      location=location.belowbar,
      size=size.small)
alertcondition (extreme_low,
   title="Stoch Extreme Low",
   message="BUY low - {{ticker}}, {{interval}} / Stop @15 PiP's + Spread")

extreme_high = (d[1]<k[1] and d>k) and 
   (( k>stoch_high ) or ( d>stoch_high ))
plotshape(extreme_high,
      style=shape.xcross,
      color=#EF5350,
      location=location.abovebar,
      size=size.small)
alertcondition (extreme_high,
   title="Stoch Extreme High",
   message="SELL high - {{ticker}}, {{interval}} / Stop @15 PiP's + Spread")
