//@version=6
// © barrett38
indicator(title = 'Stochastic Extremes', shorttitle = 'Stoch-Extremes', overlay = true, timeframe = '')

// STOCHASTIC
stochLevel = input.int(16, title = 'Stoch Level, Default at 16', minval = 1, step = 1)
stoch_low = 35 - stochLevel
stoch_high = 65 + stochLevel

k = ta.sma(ta.stoch(close, high, low, input.int(17, title = 'K', minval = 1)), 3)
d = ta.sma(k, input.int(3, title = 'D', minval = 1))

extreme_low = k[1] < d[1] and k > d and (k < stoch_low or d < stoch_low)
plotshape(extreme_low, style = shape.xcross, color = color.new(#26A69A, 0), location = location.belowbar, size = size.small)
alertcondition(extreme_low, title = 'Stoch Extreme Low', message = 'BUY low - {{ticker}}, {{interval}} / Stop @15 PiP\'s + Spread')

extreme_high = d[1] < k[1] and d > k and (k > stoch_high or d > stoch_high)
plotshape(extreme_high, style = shape.xcross, color = color.new(#EF5350, 0), location = location.abovebar, size = size.small)
alertcondition(extreme_high, title = 'Stoch Extreme High', message = 'SELL high - {{ticker}}, {{interval}} / Stop @15 PiP\'s + Spread')
