//@version=5
indicator(title="Stochastic", shorttitle="Stoch", format=format.price, precision=2, timeframe="", timeframe_gaps=true)

periodK = input.int(17, title="%K Length", minval=1)
smoothK = input.int(1, title="%K Smoothing", minval=1)
periodD = input.int(3, title="%D Smoothing", minval=1)
crossDuration = input.int(3, title="Bars to Highlight After Cross", minval=1)

k = ta.sma(ta.stoch(close, high, low, periodK), smoothK)
d = ta.sma(k, periodD)

plot(k, title="%K", color=#2962FF)
plot(d, title="%D", color=#FF6D00)

h0 = hline(80, "Upper Band", color=#787B86)
hline(50, "Middle Band", color=color.new(#787B86, 50))
h1 = hline(20, "Lower Band", color=#787B86)
fill(h0, h1, color=color.rgb(33, 150, 243, 90), title="Background")

// Track cross events and make background stay for 'crossDuration' bars
barsSinceCrossUp = ta.barssince(ta.crossover(k, d))
barsSinceCrossDown = ta.barssince(ta.crossunder(k, d))

bgcolor(barsSinceCrossUp >= 0 and barsSinceCrossUp < crossDuration ? color.new(color.green, 50) : na)
bgcolor(barsSinceCrossDown >= 0 and barsSinceCrossDown < crossDuration ? color.new(color.red, 50) : na)
